Ignore Touchpad: settings.h File Reference
settings.h File Reference
#include <Errors.h>
#include <Locker.h>
#include <Messenger.h>
#include <String.h>
#include <iostream>
#include <unordered_map>
Classes
struct DeviceInfo
Functions
DeviceInfo (BString in)
Settings (BMessenger *target=NULL, bool startMonitoring=false)
~Settings ()
void Save () const
void Load ()
bool GetStatus (BString deviceName)
status_t StartMonitoring ()
void StopMonitoring ()
void SetNotifyTarget (BMessenger *target)
status_t CreateSettingsFile () const
Service function for creating a default file with settings. All devices are enabled.
BPath * GetPathToSettingsFile ()
Service function that builds path to the settings file.
Variables
const char * fileName = "IgnoreTouchpad"
BString name
bool disabled
std::unordered_map< BString, bool > fDevicesStatus
Structure that holds status of individual devices.
BMessenger * fTarget
What BMessenger should be notified? Can be NULL.
bool fMonitoringActive
BLocker fLock
Used for updating the settings. Probably overkill, since I use BFile::Lock() as well.
Function Documentation
CreateSettingsFile()
status_t CreateSettingsFile () const protected
Service function for creating a default file with settings. All devices are enabled.
Referenced by StartMonitoring().
DeviceInfo()
Settings::DeviceInfo (BString in)
Definition at line 24 of file settings.h.
{
        name = in;
        disabled = false;
    }
GetPathToSettingsFile()
BPath * Settings::GetPathToSettingsFile () protected
Service function that builds path to the settings file.
Definition at line 110 of file settings.cpp.
References del_InputDevice(), fileName, and GetPathToSettingsFile().
Referenced by GetPathToSettingsFile(), and StartMonitoring().
GetStatus()
bool GetStatus (BString deviceName)
Load()
void Load ()
Save()
void Save () const
SetNotifyTarget()
void Settings::SetNotifyTarget (BMessenger * target)
Updates the target to send notifications to.
Definition at line 56 of file settings.cpp.
{
    fTarget = in;
}
References fTarget.
Referenced by Settings(), and ~Settings().
Settings()
Settings::Settings (BMessenger * target = NULL, bool startMonitoring = false)
Constructor.
Parameters
[in] target BMessenger to be notified when the settings file is updated.
[in] startMonitoring If true, the monitoring is started right away. Requires target to be not NULL.
Definition at line 34 of file settings.cpp.
                                                                          :
        fLock("Monitoring")
{
    fDevicesStatus.clear();
    this->SetNotifyTarget(target);
    if (target && startMonitoring) {
        StartMonitoring();
    }
}
References fDevicesStatus, SetNotifyTarget(), and StartMonitoring().
StartMonitoring()
status_t Settings::StartMonitoring ()
Starts monitoring the settings file for changes.
When the settings file is updated, the target BMessenger receives a message from Storage Kit.
See also
watch_node()
Returns
B_OK If monitoring is already active or if it was started successfully. B_BAD_HANDLER If the target BMessenger is NULL. B_BAD_VALUE If Settings::GetPathToSettingsFile() returned NULL. B_ENTRY_NOT_FOUND If the settings file couldn't be created for some reason. Some other error If could not get node ref inside critical section or if monitoring could not be started.
Definition at line 72 of file settings.cpp.
{
    if (! fTarget) { return B_BAD_HANDLER; }
    if (fMonitoringActive) { return B_OK; }
    BPath* pathToSettingsFile = GetPathToSettingsFile();
    if (! pathToSettingsFile) { return B_BAD_VALUE; }
    // ---==< Entering critical section >==---
    fLock.Lock();
    // Find the settings file
    BEntry entry(pathToSettingsFile.Path(), true);
    if (!entry.Exists()) {
        // There's no settings file
        if ( B_OK != CreateSettingsFile()) {
            fLock.Unlock();
            return B_ENTRY_NOT_FOUND;
        }
    }
    // Get the node reference
    node_ref nref;
    status_t status = entry.GetNodeRef(&nref);
    if (B_OK != status) { fLock.Unlock(); return status; }
    // Start monitoring
    status = watch_node(&fNodeRef, B_WATCH_STAT, target);
    if (status == B_OK) {
        fMonitoringActive = true;
    }
    fLock.Unlock();
    // ---==< Exitting critical section >==---
    return status;
}
References CreateSettingsFile(), fLock, fMonitoringActive, fTarget, and GetPathToSettingsFile().
Referenced by Settings().
StopMonitoring()
void StopMonitoring ()
Referenced by ~Settings().
~Settings()
Settings::~Settings ()
Destructor.
Just clears some memory. Probably unnecessary, but a good practice anyway.
Definition at line 48 of file settings.cpp.
                    {
    if (fMonitoringActive)  {   StopMonitoring(), SetNotifyTarget(NULL);    }
    fDevicesStatus.clear();
}
References fDevicesStatus, fMonitoringActive, SetNotifyTarget(), and StopMonitoring().
Variable Documentation
disabled
bool disabled
Definition at line 22 of file settings.h.
fDevicesStatus
std::unordered_map<BString, bool> fDevicesStatus protected
Structure that holds status of individual devices.
key (BString) — the device name as reported by input_server.
value (bool) — true if the device is ignored, false otherwise.
Definition at line 61 of file settings.h.
Referenced by Settings(), and ~Settings().
fileName
const char* fileName = "IgnoreTouchpad"
Definition at line 16 of file settings.h.
Referenced by GetPathToSettingsFile().
fLock
BLocker fLock protected
Used for updating the settings. Probably overkill, since I use BFile::Lock() as well.
Definition at line 66 of file settings.h.
Referenced by StartMonitoring().
fMonitoringActive
bool fMonitoringActive protected
true if monitoring is currently active, false otherwise.
Definition at line 64 of file settings.h.
Referenced by StartMonitoring(), and ~Settings().
fTarget
BMessenger* fTarget protected
What BMessenger should be notified? Can be NULL.
Definition at line 63 of file settings.h.
Referenced by SetNotifyTarget(), and StartMonitoring().
name
BString name
Definition at line 21 of file settings.h.